name: Build AUR Package

on:
  workflow_call:
    inputs:
      package_name:
        description: 'Name of the AUR package to build'
        required: true
        type: string
      dependencies:
        description: 'Comma-separated list of package dependencies'
        required: false
        type: string
        default: ''

jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged

    steps:
      - name: Update pacman
        run: pacman -Syu --noconfirm

      - name: Install dependencies
        run: pacman -S git base-devel devtools --noconfirm
      
      - name: Add build user
        run: useradd -m build

      - name: Give build unlimited power
        run: echo "build ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/build

      - name: Download and install dependencies
        if: ${{ inputs.dependencies != '' }}
        run: |
          IFS=',' read -ra deps <<< "${{ inputs.dependencies }}"
          for dep in "${deps[@]}"; do
            echo "Downloading $dep"
            curl -LO "https://github.com/gromit1/testing-action/releases/download/latest/${dep}-package.tar.zst"
          done
          pacman -U ./*.pkg.tar.zst --noconfirm

      - name: Download package
        run: git clone https://aur.archlinux.org/${{ inputs.package_name }}.git

      - name: Give build user perms
        run: chown -R build:build ${{ inputs.package_name }}

      - name: Build in clean chroot
        run: su build -c "cd ${{ inputs.package_name }} && makepkg -s --noconfirm"

      - name: Remove colons from filename
        run: |
          find ${{ inputs.package_name }} -name "*.pkg.tar.zst" -print0 | xargs -0 -I {} sh -c 'mv "{}" "$(echo "{}" | tr ":" "-")"'

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ inputs.package_name }}-package
          path: ${{ inputs.package_name }}/*.pkg.tar.zst
