# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: archlinux
      options: --privileged

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: update pacman
        run: pacman -Syu --noconfirm

      - name: install git
        run: pacman -S git base-devel devtools --noconfirm

      - name: add build user
        run: useradd -m build

      - name: give build unlimited power
        run: |
          echo "build ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/build
      
      - name: download package
        run: git clone https://aur.archlinux.org/snapd.git

      - name: give build user perms
        run: chown -R build:build yay

      - name: build in clean chroot
        run: su build -c "cd snapd && makepkg -s --noconfirm"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: snapd-package
          path: snapd/*.pkg.tar.zst
          
