name: Build AUR Package

on:
  workflow_call:
    inputs:
      package_name:
        description: 'Name of the AUR package to build'
        required: true
        type: string
      dependencies:
        description: 'Comma-separated list of package dependency names (without -package suffix)'
        required: false
        type: string
        default: ''

jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged

    steps:
      - name: Update pacman
        run: pacman -Syu --noconfirm

      - name: Install dependencies
        run: pacman -S git base-devel devtools --noconfirm

      - name: Add build user
        run: useradd -m build

      - name: Give build unlimited power
        run: |
          echo "build ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/build

      - name: Generate Download Steps
        if: ${{ inputs.dependencies != '' }}
        id: generate_download_steps
        run: |
          DEPENDENCIES="${{ inputs.dependencies }}"
          IFS=',' read -r -a DEPENDENCY_LIST <<< "$DEPENDENCIES"

          for dep in "${DEPENDENCY_LIST[@]}"; do
            artifact_name="${dep}-package"
            download_path="${{ runner.temp }}/dependencies/$dep"
            mkdir -p "$download_path"

            echo "::add-step name=Download artifact - $dep"
            echo "::add-step uses=actions/download-artifact@v4"
            echo "::add-step with.name=$artifact_name"
            echo "::add-step with.path=$download_path"
            echo "::end-step"
          done

      - name: install packages
        if: ${{ inputs.dependencies != '' }}
        run: |
          ls -R ${{ runner.temp }}/dependencies/
          pacman -U ${{ runner.temp }}/dependencies/*/*/*.pkg.tar.zst --noconfirm

      - name: Download package
        run: git clone https://aur.archlinux.org/${{ inputs.package_name }}.git

      - name: Give build user perms
        run: chown -R build:build ${{ inputs.package_name }}

      - name: Build in clean chroot
        run: su build -c "cd ${{ inputs.package_name }} && makepkg -s --noconfirm"

      - name: Remove colons from filename
        run: |
          find ${{ inputs.package_name }} -name "*.pkg.tar.zst" -print0 | xargs -0 -I {} sh -c 'if [[ "{}" == *:* ]]; then mv "{}" "$(echo "{}" | sed "s/\([^-]\):/\1-/g")"; fi'

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.package_name }}-package
          path: ${{ inputs.package_name }}/*.pkg.tar.zst
