name: AUR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  yay:
    runs-on: ubuntu-latest

    container:
      image: archlinux
      options: --privileged

    steps:
      - name: update pacman
        run: pacman -Syu --noconfirm

      - name: install git
        run: pacman -S git base-devel devtools perl-rename --noconfirm

      - name: add build user
        run: useradd -m build

      - name: give build unlimited power
        run: |
          echo "build ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/build
      
      - name: download package
        run: git clone https://aur.archlinux.org/yay.git

      - name: give build user perms
        run: chown -R build:build yay

      - name: build package
        run: su build -c "cd yay && makepkg -s --noconfirm"
    
      - name: remove colons
        run: perl-rename 's|:|-|g' yay/*.pkg.tar.zst

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: yay-package
          path: yay/*.pkg.tar.zst
