name: Build AUR Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-icoextract:
    uses: ./.github/workflows/build-aur-package.yml
    with:
      package_name: icoextract

  build-patool:
    uses: ./.github/workflows/build-aur-package.yml
    with:
      package_name: patool

  build-python-annexremote:
    uses: ./.github/workflows/build-aur-package.yml
    with:
      package_name: python-annexremote

  build-python-looseversion:
    uses: ./.github/workflows/build-aur-package.yml
    with:
      package_name: python-looseversion

  build-python-types-requests:
    uses: ./.github/workflows/build-aur-package.yml
    with:
      package_name: python-types-requests

  build-python-backoff:
    uses: ./.github/workflows/build-aur-package.yml
    with:
      package_name: python-backoff

  build-python-injector:
    uses: ./.github/workflows/build-aur-package.yml
    with:
      package_name: python-injector

  build-python-datalad:
    needs: [build-patool, build-python-annexremote, build-python-looseversion, build-python-types-requests]
    uses: ./.github/workflows/build-aur-package.yml
    with:
      package_name: python-datalad
      dependencies: patool,python-annexremote,python-looseversion,python-types-requests

  build-python-segment-analytics:
    needs: build-python-backoff
    uses: ./.github/workflows/build-aur-package.yml
    with:
      package_name: python-segment-analytics
      dependencies: python-backoff

  build-gkraken:
    needs: build-python-injector
    uses: ./.github/workflows/build-aur-package.yml
    with:
      package_name: gkraken
      dependencies: python-injector
