name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - name: yay
            repo: https://aur.archlinux.org/yay.git
          - name: snapd
            repo: https://aur.archlinux.org/snapd.git
          - name: axu
            repo: https://aur.archlinux.org/axu.git
          - name: blender-launcher-git
            repo: https://aur.archlinux.org/blender-launcher-git.git
          - name: checkupdatify
            repo: https://aur.archlinux.org/checkupdatify.git
          - name: etwas
            repo: https://aur.archlinux.org/etwas.git
          - name: idos-package-updater-script
            repo: https://aur.archlinux.org/idos-package-updater-script.git
          - name: pak-git
            repo: https://aur.archlinux.org/pak-git.git
          - name: paxs
            repo: https://aur.archlinux.org/paxs.git
          - name: pcmn-git
            repo: https://aur.archlinux.org/pcmn-git.git
          - name: pkm
            repo: https://aur.archlinux.org/pkm.git
          - name: spm-arch
            repo: https://aur.archlinux.org/spm-arch.git
          - name: ualsv
            repo: https://aur.archlinux.org/ualsv.git
          - name: yayfzf
            repo: https://aur.archlinux.org/yayfzf.git

    container:
      image: archlinux
      options: --privileged

    steps:
      - name: Update pacman
        run: pacman -Syu --noconfirm

      - name: Install dependencies
        run: pacman -S git base-devel devtools --noconfirm

      - name: Add build user
        run: useradd -m build

      - name: Grant build user sudo privileges
        run: echo "build ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/build

      - name: Download ${{ matrix.package.name }} package
        run: git clone ${{ matrix.package.repo }} ${{ matrix.package.name }}

      - name: Grant build user permissions
        run: chown -R build:build ${{ matrix.package.name }}

      - name: Build ${{ matrix.package.name }} package
        if: matrix.package.name != 'yay' && matrix.package.name != 'snapd'
        run: |
          pacman -U yay/*.pkg.tar.zst --noconfirm
          su build -c "cd ${{ matrix.package.name }} && makepkg -s --noconfirm"
      
      - name: Build ${{ matrix.package.name }} package (yay, snapd)
        if: matrix.package.name == 'yay' || matrix.package.name == 'snapd'
        run: su build -c "cd ${{ matrix.package.name }} && makepkg -s --noconfirm"

      - name: Upload ${{ matrix.package.name }} package artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ matrix.package.name }}-package
          path: ${{ matrix.package.name }}/*.pkg.tar.zst
