
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  jdk12-openjdk:
    runs-on: ubuntu-latest
    needs: [jre12-openjdk]
    container:
      image: archlinux
      options: --privileged

    steps:
      - name: update pacman
        run: pacman -Syu --noconfirm

      - name: install git
        run: pacman -S git base-devel devtools --noconfirm

      - name: add build user
        run: useradd -m build

      - name: give build unlimited power
        run: |
          echo "build ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/build

      - name: download jre12-openjdk
        uses: actions/download-artifact@v4.1.8
        with:
          name: jre12-openjdk-package

      - name: install dependencies
        run: pacman -U --noconfirm *.pkg.tar.zst

      - name: download package
        run: git clone https://aur.archlinux.org/jdk12-openjdk.git

      - name: give build user perms
        run: chown -R build:build jdk12-openjdk

      - name: build in clean chroot
        run: su build -c "cd jdk12-openjdk && makepkg -s --noconfirm --skippgpcheck"

      - name: remove semicolons
        run: rename ':' '-' jdk12-openjdk/*.tar.zst || [ $? -eq 4 ]

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: jdk12-openjdk-package
          path: jdk12-openjdk/*.pkg.tar.zst

  jre12-openjdk:
    runs-on: ubuntu-latest
    needs: [jre12-openjdk-headless]
    container:
      image: archlinux
      options: --privileged

    steps:
      - name: update pacman
        run: pacman -Syu --noconfirm

      - name: install git
        run: pacman -S git base-devel devtools --noconfirm

      - name: add build user
        run: useradd -m build

      - name: give build unlimited power
        run: |
          echo "build ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/build

      - name: download jre12-openjdk-headless
        uses: actions/download-artifact@v4.1.8
        with:
          name: jre12-openjdk-headless-package

      - name: install dependencies
        run: pacman -U --noconfirm *.pkg.tar.zst

      - name: download package
        run: git clone https://aur.archlinux.org/jre12-openjdk.git

      - name: give build user perms
        run: chown -R build:build jre12-openjdk

      - name: build in clean chroot
        run: su build -c "cd jre12-openjdk && makepkg -s --noconfirm --skippgpcheck"

      - name: remove semicolons
        run: rename ':' '-' jre12-openjdk/*.tar.zst || [ $? -eq 4 ]

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: jre12-openjdk-package
          path: jre12-openjdk/*.pkg.tar.zst

  jre12-openjdk-headless:
    runs-on: ubuntu-latest

    container:
      image: archlinux
      options: --privileged

    steps:
      - name: update pacman
        run: pacman -Syu --noconfirm

      - name: install git
        run: pacman -S git base-devel devtools --noconfirm

      - name: add build user
        run: useradd -m build

      - name: give build unlimited power
        run: |
          echo "build ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/build


      - name: download package
        run: git clone https://aur.archlinux.org/jre12-openjdk-headless.git

      - name: give build user perms
        run: chown -R build:build jre12-openjdk-headless

      - name: build in clean chroot
        run: su build -c "cd jre12-openjdk-headless && makepkg -s --noconfirm --skippgpcheck"

      - name: remove semicolons
        run: rename ':' '-' jre12-openjdk-headless/*.tar.zst || [ $? -eq 4 ]

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: jre12-openjdk-headless-package
          path: jre12-openjdk-headless/*.pkg.tar.zst
