
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  element-desktop-git:
    runs-on: ubuntu-latest

    container:
      image: archlinux
      options: --privileged

    steps:
      - name: update pacman
        run: pacman -Syu --noconfirm

      - name: install git
        run: pacman -S git base-devel devtools --noconfirm

      - name: add build user
        run: useradd -m build

      - name: give build unlimited power
        run: |
          echo "build ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/build

      - name: download package
        run: git clone https://aur.archlinux.org/element-desktop-git.git

      - name: give build user perms
        run: chown -R build:build element-desktop-git

      - name: build in clean chroot
        run: su build -c "cd element-desktop-git && makepkg -s --noconfirm"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: element-desktop-git-package
          path: element-desktop-git/*.pkg.tar.zst
